import os
import sqlite3
import json
from datetime import datetime
from ollama import Client
from rich.console import Console
from rich.table import Table
from rich.prompt import Prompt, IntPrompt
from rich.panel import Panel

# Configuration
DB_PATH = "data/jobs.db"
LOG_PATH = "logs/applications_sent.log"
CV_PATH = "docs/my_cv.pdf"
OLLAMA_HOST = "http://localhost:11434"
MODEL_NAME = "mistral"

YOUR_SKILLS = """
Python, Cybersecurity, Helpdesk, GPT, FastAPI, API Automation, AI tools
"""

client = Client(host=OLLAMA_HOST)
console = Console()

def fetch_top_te_jobs(limit=5):
    con = sqlite3.connect(DB_PATH)
    cur = con.cursor()
    rows = cur.execute("""
        SELECT id, title, url, raw, score FROM jobs 
        WHERE source = 'te' AND score IS NOT NULL 
        ORDER BY score DESC 
        LIMIT ?
    """, (limit,)).fetchall()
    con.close()
    return rows

def display_jobs(rows):
    table = Table(title="🎯 Top TE Jobs by Score", show_lines=True)
    table.add_column("No", justify="center", style="cyan")
    table.add_column("Job ID", style="magenta")
    table.add_column("Title", style="green")
    table.add_column("Score", justify="center", style="yellow")

    for i, (job_id, title, _, _, score) in enumerate(rows, 1):
        table.add_row(str(i), job_id, title, str(score))

    console.print(table)

def already_applied(job_id):
    if not os.path.exists(LOG_PATH):
        return False
    with open(LOG_PATH, "r") as f:
        return any(job_id in line for line in f.readlines())

def generate_cover_letter(description):
    prompt = f"""
Write a short, personalized cover letter using the following information:

MY SKILLS:
{YOUR_SKILLS}

JOB DESCRIPTION:
{description}

Tone: Friendly, Motivated, Professional.
Length: Under 200 words.
"""
    response = client.chat(
        model=MODEL_NAME,
        messages=[{"role": "user", "content": prompt}]
    )
    return response['message']['content'].strip()

def log_application(job_id, url):
    os.makedirs(os.path.dirname(LOG_PATH), exist_ok=True)
    with open(LOG_PATH, "a") as log:
        log.write(f"{job_id} | {url} | {datetime.now().isoformat()}\n")

def main():
    console.print("[bold cyan]\n📋 Fetching Top Scored TE Jobs...[/bold cyan]")
    rows = fetch_top_te_jobs()
    display_jobs(rows)

    try:
        choice = IntPrompt.ask("\n📥 Enter the number of the job to apply to", choices=[str(i) for i in range(1, len(rows)+1)])
    except Exception:
        console.print("[red]❌ Invalid input. Exiting.[/red]")
        return

    job_id, title, url, raw_json, score = rows[choice-1]

    if already_applied(job_id):
        console.print(f"[yellow]⛔ Already applied to job ID:[/yellow] {job_id}")
        return

    job_data = json.loads(raw_json)
    description = job_data.get("description", "")
    cover_letter = generate_cover_letter(description)

    console.print(f"\n[bold green]📤 Applying to:[/bold green] {title}")
    console.print(f"🔗 [underline]{url}[/underline]")
    console.print(f"📎 CV: {CV_PATH}")

    console.print(Panel(cover_letter, title="📝 Cover Letter", subtitle="Generated by Ollama", border_style="blue"))

    log_application(job_id, url)
    console.print("\n[bold green]✅ Application simulated and logged.[/bold green]")

if __name__ == "__main__":
    main()
